package video

import (
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strconv"

	"github.com/pixelog/pixelog-go-v1/backend/pkg/config"
)

type Maker struct{}

type Metadata struct {
	Version     string         `json:"version"`
	CreatedAt   string         `json:"created_at"`
	TotalChunks int            `json:"total_chunks"`
	Contents    []ContentItem  `json:"contents"`
	Config      *config.Config `json:"config"`
}

type ContentItem struct {
	Name      string `json:"name"`
	Type      string `json:"type"`
	Size      string `json:"size"`
	Hash      string `json:"hash"`
	CreatedAt string `json:"created_at"`
}

func New() (*Maker, error) {
	// Check if ffmpeg is available
	if _, err := exec.LookPath("ffmpeg"); err != nil {
		return nil, fmt.Errorf("ffmpeg not found in PATH: %w", err)
	}

	return &Maker{}, nil
}

func (m *Maker) CreateVideo(framePaths []string, outputPath string, metadata interface{}, cfg *config.Config) error {
	if len(framePaths) == 0 {
		return fmt.Errorf("no frames to process")
	}

	// Create a temporary directory for the frame sequence
	tempDir := filepath.Dir(framePaths[0])

	// Create metadata file
	metadataPath := filepath.Join(tempDir, "metadata.json")
	metadataData, err := json.MarshalIndent(metadata, "", "  ")
	if err != nil {
		return fmt.Errorf("failed to marshal metadata: %w", err)
	}

	if err := os.WriteFile(metadataPath, metadataData, 0644); err != nil {
		return fmt.Errorf("failed to write metadata: %w", err)
	}

	// Build ffmpeg command
	args := []string{
		"-y", // Overwrite output file
		"-framerate", fmt.Sprintf("%.2f", cfg.FrameRate),
		"-i", filepath.Join(tempDir, "frame_%05d.png"),
		"-f", "lavfi", "-i", "anullsrc=channel_layout=stereo:sample_rate=48000",
		"-c:v", "libx264",
		"-pix_fmt", "yuv420p",
		"-crf", strconv.Itoa(cfg.Quality),
		"-preset", "medium",
		"-c:a", "aac",
		"-b:a", "128k",
		"-shortest",
		"-movflags", "+faststart",
		"-metadata", "title=Pixelog Knowledge File",
		"-metadata", "comment=Generated by Pixelog v1.0.0",
		outputPath,
	}

	cmd := exec.Command("ffmpeg", args...)

	if cfg.Verbose {
		cmd.Stdout = os.Stdout
		cmd.Stderr = os.Stderr
	}

	if err := cmd.Run(); err != nil {
		return fmt.Errorf("ffmpeg command failed: %w", err)
	}

	// Clean up metadata file
	os.Remove(metadataPath)

	return nil
}

func (m *Maker) ExtractData(inputPath, outputDir string) error {
	// This would extract frames from the video and decode QR codes
	// For now, implement a placeholder
	return fmt.Errorf("extraction not implemented yet")
}

func (m *Maker) ExtractMetadata(inputPath string) (*Metadata, error) {
	// This would extract metadata from the video file
	// For now, implement a placeholder
	return nil, fmt.Errorf("metadata extraction not implemented yet")
}
